# Generated by Django 4.2.4 on 2023-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0003_alter_disasterentry_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterentry',
            name='send_to',
            field=models.CharField(choices=[('rescue_team', 'rescue_team'), ('police_team', 'police_team'), ('revenue_team', 'revenue_team'), ('CEO', 'CEO'), ('DHO', 'DHO')], max_length=20, null=True),
        ),
    ]
