# Generated by Django 4.2.4 on 2023-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_app', '0007_taluka_village_wadi_alter_disasterentry_taluka_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterentry',
            name='send_to',
            field=models.CharField(max_length=500, null=True, verbose_name='Teams'),
        ),
    ]
